apiVersion: v1
data:
  accesskey: YWRtaW4=
  secretkey: YWRtaW5AMTIz 
kind: Secret
metadata:
  name: minio-creds-secret

---
apiVersion: v1
data:
  files: {{ .Files.Get "configs/file.toml" | b64enc }}
kind: Secret
metadata:
  name: filesconf



---
apiVersion: v1
data:
  jmeter-conf.jmx: {{ .Files.Get "configs/jmeter-conf.toml" | b64enc }}
kind: Secret
metadata:
  name: jmeterconf