apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
{{ include "common-resources.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8088
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app: influxdb
    release: {{ .Release.Name }}