apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: grafana-creds


---
apiVersion: v1
data:
  MINIO_ACCESS_KEY: YWRtaW4=
  MINIO_SECRET_KEY: YWRtaW4=
kind: Secret
metadata:
  name: minio-creds
