apiVersion: v1
data:
  password: YWRtaW5AMTIz 
  username: YWRtaW4=
kind: Secret
metadata:
  name: grafana-creds


---
apiVersion: v1
data:
  MINIO_ACCESS_KEY: YWRtaW4=
  MINIO_SECRET_KEY: YWRtaW5AMTIz 
kind: Secret
metadata:
  name: minio-creds

---
apiVersion: v1
data:
  init-influxdb.iql: {{ .Files.Get "configs/init-influxdb.toml" | b64enc }}
kind: Secret
metadata:
  name: init-script

