{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common-resources.serviceAccountName" . }}
  labels:
{{ include "common-resources.labels" . | indent 4 }}
{{- end -}}
