apiVersion: batch/v1
kind: Job
metadata:
  name: jmeterjob
  labels:
    env: test
    jobgroup: jmeter
spec:

  parallelism: {{ .Values.replicaCount }}

  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: jmeter
      labels:
        jobgroup: jmeter  
    spec:
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "jmeter"
        effect: "NoSchedule"       
      containers:
      - name: jmeter

        image:  shashanksinha/docker-jmeter-c-icap:2
        command: [ "bash", "-c", "JVM_ARGS='-Xms1024m -Xmx3072m' /usr/local/apache-jmeter-5.3/bin/jmeter.sh -n -t /usr/share/jmx/jmeter-conf.jmx -l /usr/share/Test/report/icap.jtl -j /usr/share/Test/report/jmeter.log"]

        resources:
          requests:
            memory: "3500Mi"
            cpu: "1000m"
          limits:
            memory: "3500Mi"
            cpu: "1000m"
        imagePullPolicy: Always
        env:
          # Source Minio Infromation
          - name: TARGET_MINIO_URL
            value: "http://minio-service.common"
          - name: TARGET_MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds-secret
                key: accesskey
          - name: TARGET_MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds-secret
                key: secretkey
          - name: TARGET_MINIO_BUCKET
            value: output
          # Log Level (Default to Info)
          - name: LOG_LEVEL
            value: info
          # Environment info
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          # JVM
          - name: JVM_ARGS
            value: "-Xms1024m -Xmx2048m"
        volumeMounts:
        - name: jmetervol
          mountPath: "/usr/share/jmx"
          readOnly: true
        - name: filesvol
          mountPath: "/usr/share/data"
          readOnly: true
      volumes:
      - name: jmetervol
        secret:
          secretName: jmeterconf          
      - name: filesvol
        secret:
          secretName: filesconf
      restartPolicy: Never