dependencies:
  - name: prometheus
    version: 11.12.1
    repository: "https://charts.helm.sh/stable"
  - name: loki
    version: 2.1.0
    repository: "https://grafana.github.io/loki/charts"
  - name: promtail
    version: 2.0.1
    repository: "https://grafana.github.io/loki/charts"