apiVersion: v1
kind: Service
metadata:
  name: influxdb-lb-svc
  namespace: common
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
  selector:
    app: influxdb
  loadBalancerSourceRanges:
  - 127.0.0.1/32