
{{- if eq .Values.cloud "aws" }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: gp2
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"

{{ end }}

{{- if eq .Values.cloud "local" }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: {{ .Values.grafana.storageclass  }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.grafana.storage }}

{{ end }}
