{{- if eq .Values.cloud "aws" }}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-influx
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-influx
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-influx
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{  .Values.minio.pv.ebs_volume_id }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-influx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-influx
  resources:
    requests:
      storage: 10Gi

{{ end }}

{{- if eq .Values.cloud "azure" }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-influx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi

{{ end }}

{{- if eq .Values.cloud "local" }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-influx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/influxdb"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-influx
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"

{{ end }}