apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-storage
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-file-storage
  resources:
    requests:
      storage: 5Gi