--- 
    apiVersion: apps/v1
    kind: Deployment
    metadata: 
      annotations: 
        deployment.kubernetes.io/revision: "2"
        kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"minio\",\"namespace\":\"minio\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"minio\"}},\"strategy\":{\"type\":\"Recreate\"},\"template\":{\"metadata\":{\"labels\":{\"app\":\"minio\"}},\"spec\":{\"containers\":[{\"args\":[\"server\",\"/data\"],\"env\":[{\"name\":\"MINIO_ACCESS_KEY\",\"value\":\"test\"},{\"name\":\"MINIO_SECRET_KEY\",\"value\":\"test@123\"}],\"image\":\"minio/minio:RELEASE.2020-05-01T22-19-14Z\",\"name\":\"minio\",\"ports\":[{\"containerPort\":9000}]}]}}}}\n"
      creationTimestamp: "2020-10-15T05:13:40Z"
      generation: 2
      name: minio
      namespace: minio
      resourceVersion: "799337"
      selfLink: /apis/apps/v1/namespaces/minio/deployments/minio
      uid: 37d2997e-c679-4e98-b8fc-6aae263f026e
    spec: 
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector: 
        matchLabels: 
          app: minio
      strategy: 
        type: Recreate
      template: 
        metadata: 
          annotations: 
            kubectl.kubernetes.io/restartedAt: "2020-10-15T14:08:20+04:00"
          creationTimestamp: ~
          labels: 
            app: minio
        spec: 
          containers: 
            - 
              args: 
                - server
                - /data
              env: 
                - 
                  name: MINIO_ACCESS_KEY
                  valueFrom: 
                    secretKeyRef: 
                      key: MINIO_ACCESS_KEY
                      name: minio-creds
                - 
                  name: MINIO_SECRET_KEY
                  valueFrom: 
                    secretKeyRef: 
                      key: MINIO_SECRET_KEY
                      name: minio-creds
              image: "minio/minio:RELEASE.2020-05-01T22-19-14Z"
              imagePullPolicy: IfNotPresent
              name: minio
              ports: 
                - 
                  containerPort: 9000
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts: 
                - 
                  mountPath: /data
                  name: azure-file-storage
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes: 
            - 
              emptyDir: {}
              name: azure-file-storage
    status: 
      availableReplicas: 1
      conditions: 
        - 
          lastTransitionTime: "2020-10-15T05:13:40Z"
          lastUpdateTime: "2020-10-15T10:08:28Z"
          message: "ReplicaSet \"minio-786cbf5868\" has successfully progressed."
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
        - 
          lastTransitionTime: "2020-10-18T15:49:08Z"
          lastUpdateTime: "2020-10-18T15:49:08Z"
          message: "Deployment has minimum availability."
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
      observedGeneration: 2
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
    
